---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-infra
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/egormak/flux-infra

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-infra
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/egorka
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-infra
  # postBuild:
  #   substitute:
  #     env: "homelab"
  #     cluster_name: "docker-desktop"
  #     cluster_subdomain: "localhost.direct"