---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-infra-crd
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/egorka-crd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-infra
  # postBuild:
  #   substitute:
  #     env: "homelab"
  #     cluster_name: "docker-desktop"
  #     cluster_subdomain: "localhost.direct"